### ISSUE TITLE
Error happen when trying to download Photoshop and Illustrator

### ISSUE THREAD

**Issue by gungkrisna** [Drovosek01/adobe-packager#13]
However, it doesn't happen when I download Premiere Pro and After Effect through the script.

```
Traceback (most recent call last):
  File "./ccdl.py", line 615, in <module>
    runccdl()
  File "./ccdl.py", line 551, in runccdl
    if ((not pkg.get('Condition')) or installLanguage in pkg['Condition'] or oslang in pkg['Condition']):
TypeError: 'in <string>' requires string as left operand, not NoneType

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by kahn2k** [comment]
Yes, I have the same error

**Comment by juniarz** [comment]
I fixed this by changing `line 551 in ./ccdl.py file`:

`if ((not pkg.get('Condition')) or pkg['Condition'].find(installLanguage)):`

the pkg.Condition value is a string and not an array.

Please note that this is a temp fix.

**Comment by thpryrchn** [comment]
Latest Commit should have fixed this. Close the Issue if it did

**Comment by kahn2k** [comment]
Yeah, new commit fixed the issue.
