### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not NoneType

### ISSUE THREAD

**Issue by vo2lab** [Drovosek01/adobe-packager#14]
[PHSP_22.5] Parsing available packages
Traceback (most recent call last):
  File "/Users/mike/Downloads/adobe-packager/./ccdl.py", line 615, in <module>
    runccdl()
  File "/Users/mike/Downloads/adobe-packager/./ccdl.py", line 551, in runccdl
    if ((not pkg.get('Condition')) or installLanguage in pkg['Condition'] or oslang in pkg['Condition']):
TypeError: 'in <string>' requires string as left operand, not NoneType

Any idea what this is?

**Comment by juni0r** [comment]
I get the same error, no matter what product or version I try to install. This is python 3.9.7 on macOS 11.6.

**Comment by thpryrchn** [comment]
Latest Commit should have fixed this. Close the Issue if it did
