### ISSUE TITLE
Downloading an M1 installer packages it for Intel

### ISSUE THREAD

**Issue by atIOCrON** [Drovosek01/adobe-packager#18]
When downloading it asks if you want to make an app native for M1. I selected Yes and chose Photoshop. Once done, the installer was called: Install PHSP_22.4.2-en_US-macarm64.

When I opened the installer I was prompted to install Rosetta 2 which I declined because I don't want to run Rosetta 2 on this machine.

On inspection of the application it was listed as for Intel Mac's.

It seems the M1 native package doesn't actually create an M1 native installer.

**Comment by Drovosek01** [comment]
Have you checked the already installed Photoshop or is this claim only to the installer?

**Comment by rcournault** [comment]
I can download M1 package (Install PHSP_23.0.1-fr_FR-macuniversal.app) but I'have error 101 on the install

**Comment by rcournault** [comment]
I can download M1 package (Install PHSP_23.0.1-fr_FR-macuniversal.app) but I'have error 101 on the install

**Comment by thpryrchn** [comment]
You Can't Install Photoshop and not have Rosetta... There are dependency packages that are only Intel.
