### ISSUE TITLE
No After Effects before version 22.1.1

### ISSUE THREAD

**Issue by gird34** [Drovosek01/adobe-packager#21]
I wanted to use ae 2021, but the previous version just aren’t available. I’m not sure why but please fix this thank you so much

EDIT: Removed Piracy

**Comment by thpryrchn** [comment]
It does work! Make sure you are entering the right product code. I was able to download the popular version of 18.4.1 without any problems.
```
=================================
= Adobe macOS Package Generator =
============= 0.1.4 =============

Do you want to make M1 native packages (y/N): 
Downloading products.xml

https://cdn-ffc.oobesaas.adobe.com/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Source URL is: https://cdn-ffc.oobesaas.adobe.com/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Parsing products.xml
CDN: https://ccmdls.adobe.com
33 products found:

[AEFT] After Effects
[AEFTBETA] After Effects (Beta)
[AERO] Aero (Beta)
[AICY] InCopy
[AME] Media Encoder
[AMEBETA] Media Encoder (Beta)
[ANMLBETA] Character Animator CC (Beta)
[AUDT] Audition
[AUDTBETA] Audition (Beta)
[CHAR] Character Animator
[CHARBETA] Character Animator (Beta)
[DRWV] Dreamweaver
[ESHR] Dimension
[FLPR] Animate
[IDSN] InDesign
[ILST] Illustrator
[KBRG] Bridge
[LRCC] Lightroom
[LTRM] Lightroom Classic
[MUSE] Muse CC
[PHSP] Photoshop
[PHSPBETA] Photoshop (Beta)
[PPRO] Premiere Pro
[PPROBETA] Premiere Pro (Beta)
[PRLD] Prelude
[RUSH] Premiere Rush
[RUSHBETA] Premiere Rush (Beta)
[SBSTA] Substance 3D Sampler
[SBSTD] Substance 3D Designer
[SBSTP] Substance 3D Painter
[SPRK] XD
[STGR] Substance 3D Stager
[UXPD] UXP Developer Tools

Please enter the SAP Code of the desired product (eg. PHSP for Photoshop): AEFT

After Effects Platform: osx10-64 - 13.8.0
After Effects Platform: osx10-64 - 13.8.1
After Effects Platform: osx10-64 - 14.0.0
After Effects Platform: osx10-64 - 14.0.1
After Effects Platform: osx10-64 - 14.1.0
After Effects Platform: osx10-64 - 14.2.0
After Effects Platform: osx10-64 - 14.2.1
After Effects Platform: osx10-64 - 14.2.2
After Effects Platform: osx10-64 - 15.0.0
After Effects Platform: osx10-64 - 15.0.1
After Effects Platform: osx10-64 - 15.1
After Effects Platform: osx10-64 - 15.1.1
After Effects Platform: osx10-64 - 15.1.2
After Effects Platform: osx10-64 - 16.0
After Effects Platform: osx10-64 - 16.0.1
After Effects Platform: osx10-64 - 16.1
After Effects Platform: osx10-64 - 16.1.1
After Effects Platform: osx10-64 - 16.1.2
After Effects Platform: osx10-64 - 16.1.3
After Effects Platform: osx10-64 - 17.0
After Effects Platform: osx10-64 - 17.0.1
After Effects Platform: osx10-64 - 17.0.2
After Effects Platform: osx10-64 - 17.0.4
After Effects Platform: osx10-64 - 17.0.5
After Effects Platform: osx10-64 - 17.0.6
After Effects Platform: osx10-64 - 17.1
After Effects Platform: osx10-64 - 17.1.1
After Effects Platform: osx10-64 - 17.1.2
After Effects Platform: osx10-64 - 17.1.3
After Effects Platform: osx10-64 - 17.1.4
After Effects Platform: osx10-64 - 17.5
After Effects Platform: osx10-64 - 17.5.1
After Effects Platform: osx10-64 - 17.6
After Effects Platform: osx10-64 - 17.7
After Effects Platform: osx10-64 - 18.0
After Effects Platform: osx10-64 - 18.1
After Effects Platform: osx10-64 - 18.2
After Effects Platform: osx10-64 - 18.2.1
After Effects Platform: osx10-64 - 18.4
After Effects Platform: osx10-64 - 18.4.1
After Effects Platform: osx10-64 - 22.0
After Effects Platform: osx10-64 - 22.0.1
After Effects Platform: osx10-64 - 22.1.1

Please enter the desired version. Nothing for 22.1.1: 18.4.1

Available languages: en_US, en_GB, en_IL, en_AE, es_ES, es_MX, pt_BR, fr_FR, fr_CA, fr_MA, it_IT, de_DE, nl_NL, ru_RU, uk_UA, zh_TW, zh_CN, ja_JP, ko_KR, pl_PL, hu_HU, cs_CZ, tr_TR, sv_SE, nb_NO, fi_FI, da_DK, ALL

Please enter the desired install language, or nothing for [en_US]: 

Please navigate to the desired downloads folder, or cancel to abort.

sapCode: AEFT
version: 18.4.1
installLanguage: en_US
dest: /private/tmp/Install AEFT_18.4.1-en_US-osx10-64.app
[{'sapCode': 'AEFT', 'version': '18.4.1', 'buildGuid': '0409d7a6-c4e2-4284-8060-a23af9458701'}, {'sapCode': 'ACR', 'version': '9.6', 'buildGuid': '3fc409fc-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'CORG', 'version': '1.0', 'buildGuid': '3fc3cf0a-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'COMP', 'version': '1.0', 'buildGuid': '3fc3d914-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'CCXP', 'version': '2.2.1', 'buildGuid': '3fdc5e2b-c3fa-11e9-b9c5-12148b63a89a'}]

Creating Install AEFT_18.4.1-en_US-osx10-64.app

Preparing...

[AEFT_18.4.1] Downloading application.json
[AEFT_18.4.1] Creating folder for product
[AEFT_18.4.1] Saving application.json

[ACR_9.6] Downloading application.json
[ACR_9.6] Creating folder for product
[ACR_9.6] Saving application.json

[CORG_1.0] Downloading application.json
[CORG_1.0] Creating folder for product
[CORG_1.0] Saving application.json

[COMP_1.0] Downloading application.json
[COMP_1.0] Creating folder for product
[COMP_1.0] Saving application.json

[CCXP_2.2.1] Downloading application.json
[CCXP_2.2.1] Creating folder for product
[CCXP_2.2.1] Saving application.json

Downloading...

[AEFT_18.4.1] Parsing available packages
[AEFT_18.4.1] Selected 1 core packages and 0 non-core packages
Url is: https://ccmdls.adobe.com/AdobeProducts/AEFT/18.4.1.4/osx10-64/2779397e-30f1-48b4-a072-09c7debd230d/AdobeAfterEffects18AllTrial.zip
[AEFT_18.4.1] Downloading AdobeAfterEffects18AllTrial.zip
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.04G/2.04G [00:57<00:00, 35.5MiB/s]
[ACR_9.6] Parsing available packages
[ACR_9.6] Selected 3 core packages and 0 non-core packages
Url is: https://ccmdls.adobe.com/AdobeProducts/ACR/9.6.0.126/osx10-64/7c980b25-1124-4605-95cd-03a73ebd0d2a/CameraRawRIBSCoExistPackage.zip
[ACR_9.6] Downloading CameraRawRIBSCoExistPackage.zip
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63.6k/63.6k [00:00<00:00, 50.7MiB/s]
Url is: https://ccmdls.adobe.com/AdobeProducts/ACR/9.6.0.126/osx10-64/7c980b25-1124-4605-95cd-03a73ebd0d2a/AdobeCameraRaw8.0All.zip
[ACR_9.6] Downloading AdobeCameraRaw8.0All.zip
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43.9M/43.9M [00:01<00:00, 26.5MiB/s]
Url is: https://ccmdls.adobe.com/AdobeProducts/ACR/9.6.0.126/osx10-64/7c980b25-1124-4605-95cd-03a73ebd0d2a/AdobeCameraRawProfile8.0All.zip
[ACR_9.6] Downloading AdobeCameraRawProfile8.0All.zip
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226M/226M [00:03<00:00, 73.6MiB/s]
[CORG_1.0] Parsing available packages
[CORG_1.0] Selected 0 core packages and 1 non-core packages
Url is: https://ccmdls.adobe.com/AdobeProducts/CORG/1.0.4/osx10/b0e33289-2fc0-43ff-af9f-3c233f27eafc/AdobeColorCommonSetRGB_1_0-mul.zip
[CORG_1.0] Downloading AdobeColorCommonSetRGB_1_0-mul.zip
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.69k/7.69k [00:00<00:00, 15.5MiB/s]
[COMP_1.0] Parsing available packages
[COMP_1.0] Selected 0 core packages and 2 non-core packages
Url is: https://ccmdls.adobe.com/AdobeProducts/COMP/1.0.5/osx10/afb9a6ca-08d0-4322-94c8-a4c55ac83cfb/AdobeColor_MotionPicture_1_0-mul.zip
[COMP_1.0] Downloading AdobeColor_MotionPicture_1_0-mul.zip
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.54M/2.54M [00:00<00:00, 46.8MiB/s]
Url is: https://ccmdls.adobe.com/AdobeProducts/COMP/1.0.5/osx10/afb9a6ca-08d0-4322-94c8-a4c55ac83cfb/AdobeColor_VideoProfilesAE_1_0-mul.zip
[COMP_1.0] Downloading AdobeColor_VideoProfilesAE_1_0-mul.zip
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.7k/25.7k [00:00<00:00, 34.0MiB/s]
[CCXP_2.2.1] Parsing available packages
[CCXP_2.2.1] Selected 1 core packages and 0 non-core packages
Url is: https://ccmdls.adobe.com/AdobeProducts/CCXP/2.2.1.120/osx10-64/856988a2-0933-4098-9c21-082ae9d1fe8f/CCX-Process-mul.zip
[CCXP_2.2.1] Downloading CCX-Process-mul.zip
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29.1M/29.1M [00:00<00:00, 35.3MiB/s]

Generating driver.xml

Package successfully created. Run /private/tmp/Install AEFT_18.4.1-en_US-osx10-64.app to install.


Do you want to create another package (Y/n): 
```

**Comment by gird34** [comment]
> It does work! Make sure you are entering the right product code. I was able to download the popular version of 18.4.1 without any problems.
> 
> ```
> =================================
> = Adobe macOS Package Generator =
> ============= 0.1.4 =============
> 
> Do you want to make M1 native packages (y/N): 
> Downloading products.xml
> 
> https://cdn-ffc.oobesaas.adobe.com/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
> Source URL is: https://cdn-ffc.oobesaas.adobe.com/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
> Parsing products.xml
> CDN: https://ccmdls.adobe.com
> 33 products found:
> 
> [AEFT] After Effects
> [AEFTBETA] After Effects (Beta)
> [AERO] Aero (Beta)
> [AICY] InCopy
> [AME] Media Encoder
> [AMEBETA] Media Encoder (Beta)
> [ANMLBETA] Character Animator CC (Beta)
> [AUDT] Audition
> [AUDTBETA] Audition (Beta)
> [CHAR] Character Animator
> [CHARBETA] Character Animator (Beta)
> [DRWV] Dreamweaver
> [ESHR] Dimension
> [FLPR] Animate
> [IDSN] InDesign
> [ILST] Illustrator
> [KBRG] Bridge
> [LRCC] Lightroom
> [LTRM] Lightroom Classic
> [MUSE] Muse CC
> [PHSP] Photoshop
> [PHSPBETA] Photoshop (Beta)
> [PPRO] Premiere Pro
> [PPROBETA] Premiere Pro (Beta)
> [PRLD] Prelude
> [RUSH] Premiere Rush
> [RUSHBETA] Premiere Rush (Beta)
> [SBSTA] Substance 3D Sampler
> [SBSTD] Substance 3D Designer
> [SBSTP] Substance 3D Painter
> [SPRK] XD
> [STGR] Substance 3D Stager
> [UXPD] UXP Developer Tools
> 
> Please enter the SAP Code of the desired product (eg. PHSP for Photoshop): AEFT
> 
> After Effects Platform: osx10-64 - 13.8.0
> After Effects Platform: osx10-64 - 13.8.1
> After Effects Platform: osx10-64 - 14.0.0
> After Effects Platform: osx10-64 - 14.0.1
> After Effects Platform: osx10-64 - 14.1.0
> After Effects Platform: osx10-64 - 14.2.0
> After Effects Platform: osx10-64 - 14.2.1
> After Effects Platform: osx10-64 - 14.2.2
> After Effects Platform: osx10-64 - 15.0.0
> After Effects Platform: osx10-64 - 15.0.1
> After Effects Platform: osx10-64 - 15.1
> After Effects Platform: osx10-64 - 15.1.1
> After Effects Platform: osx10-64 - 15.1.2
> After Effects Platform: osx10-64 - 16.0
> After Effects Platform: osx10-64 - 16.0.1
> After Effects Platform: osx10-64 - 16.1
> After Effects Platform: osx10-64 - 16.1.1
> After Effects Platform: osx10-64 - 16.1.2
> After Effects Platform: osx10-64 - 16.1.3
> After Effects Platform: osx10-64 - 17.0
> After Effects Platform: osx10-64 - 17.0.1
> After Effects Platform: osx10-64 - 17.0.2
> After Effects Platform: osx10-64 - 17.0.4
> After Effects Platform: osx10-64 - 17.0.5
> After Effects Platform: osx10-64 - 17.0.6
> After Effects Platform: osx10-64 - 17.1
> After Effects Platform: osx10-64 - 17.1.1
> After Effects Platform: osx10-64 - 17.1.2
> After Effects Platform: osx10-64 - 17.1.3
> After Effects Platform: osx10-64 - 17.1.4
> After Effects Platform: osx10-64 - 17.5
> After Effects Platform: osx10-64 - 17.5.1
> After Effects Platform: osx10-64 - 17.6
> After Effects Platform: osx10-64 - 17.7
> After Effects Platform: osx10-64 - 18.0
> After Effects Platform: osx10-64 - 18.1
> After Effects Platform: osx10-64 - 18.2
> After Effects Platform: osx10-64 - 18.2.1
> After Effects Platform: osx10-64 - 18.4
> After Effects Platform: osx10-64 - 18.4.1
> After Effects Platform: osx10-64 - 22.0
> After Effects Platform: osx10-64 - 22.0.1
> After Effects Platform: osx10-64 - 22.1.1
> 
> Please enter the desired version. Nothing for 22.1.1: 18.4.1
> 
> Available languages: en_US, en_GB, en_IL, en_AE, es_ES, es_MX, pt_BR, fr_FR, fr_CA, fr_MA, it_IT, de_DE, nl_NL, ru_RU, uk_UA, zh_TW, zh_CN, ja_JP, ko_KR, pl_PL, hu_HU, cs_CZ, tr_TR, sv_SE, nb_NO, fi_FI, da_DK, ALL
> 
> Please enter the desired install language, or nothing for [en_US]: 
> 
> Please navigate to the desired downloads folder, or cancel to abort.
> 
> sapCode: AEFT
> version: 18.4.1
> installLanguage: en_US
> dest: /private/tmp/Install AEFT_18.4.1-en_US-osx10-64.app
> [{'sapCode': 'AEFT', 'version': '18.4.1', 'buildGuid': '0409d7a6-c4e2-4284-8060-a23af9458701'}, {'sapCode': 'ACR', 'version': '9.6', 'buildGuid': '3fc409fc-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'CORG', 'version': '1.0', 'buildGuid': '3fc3cf0a-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'COMP', 'version': '1.0', 'buildGuid': '3fc3d914-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'CCXP', 'version': '2.2.1', 'buildGuid': '3fdc5e2b-c3fa-11e9-b9c5-12148b63a89a'}]
> 
> Creating Install AEFT_18.4.1-en_US-osx10-64.app
> 
> Preparing...
> 
> [AEFT_18.4.1] Downloading application.json
> [AEFT_18.4.1] Creating folder for product
> [AEFT_18.4.1] Saving application.json
> 
> [ACR_9.6] Downloading application.json
> [ACR_9.6] Creating folder for product
> [ACR_9.6] Saving application.json
> 
> [CORG_1.0] Downloading application.json
> [CORG_1.0] Creating folder for product
> [CORG_1.0] Saving application.json
> 
> [COMP_1.0] Downloading application.json
> [COMP_1.0] Creating folder for product
> [COMP_1.0] Saving application.json
> 
> [CCXP_2.2.1] Downloading application.json
> [CCXP_2.2.1] Creating folder for product
> [CCXP_2.2.1] Saving application.json
> 
> Downloading...
> 
> [AEFT_18.4.1] Parsing available packages
> [AEFT_18.4.1] Selected 1 core packages and 0 non-core packages
> Url is: https://ccmdls.adobe.com/AdobeProducts/AEFT/18.4.1.4/osx10-64/2779397e-30f1-48b4-a072-09c7debd230d/AdobeAfterEffects18AllTrial.zip
> [AEFT_18.4.1] Downloading AdobeAfterEffects18AllTrial.zip
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.04G/2.04G [00:57<00:00, 35.5MiB/s]
> [ACR_9.6] Parsing available packages
> [ACR_9.6] Selected 3 core packages and 0 non-core packages
> Url is: https://ccmdls.adobe.com/AdobeProducts/ACR/9.6.0.126/osx10-64/7c980b25-1124-4605-95cd-03a73ebd0d2a/CameraRawRIBSCoExistPackage.zip
> [ACR_9.6] Downloading CameraRawRIBSCoExistPackage.zip
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63.6k/63.6k [00:00<00:00, 50.7MiB/s]
> Url is: https://ccmdls.adobe.com/AdobeProducts/ACR/9.6.0.126/osx10-64/7c980b25-1124-4605-95cd-03a73ebd0d2a/AdobeCameraRaw8.0All.zip
> [ACR_9.6] Downloading AdobeCameraRaw8.0All.zip
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43.9M/43.9M [00:01<00:00, 26.5MiB/s]
> Url is: https://ccmdls.adobe.com/AdobeProducts/ACR/9.6.0.126/osx10-64/7c980b25-1124-4605-95cd-03a73ebd0d2a/AdobeCameraRawProfile8.0All.zip
> [ACR_9.6] Downloading AdobeCameraRawProfile8.0All.zip
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226M/226M [00:03<00:00, 73.6MiB/s]
> [CORG_1.0] Parsing available packages
> [CORG_1.0] Selected 0 core packages and 1 non-core packages
> Url is: https://ccmdls.adobe.com/AdobeProducts/CORG/1.0.4/osx10/b0e33289-2fc0-43ff-af9f-3c233f27eafc/AdobeColorCommonSetRGB_1_0-mul.zip
> [CORG_1.0] Downloading AdobeColorCommonSetRGB_1_0-mul.zip
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.69k/7.69k [00:00<00:00, 15.5MiB/s]
> [COMP_1.0] Parsing available packages
> [COMP_1.0] Selected 0 core packages and 2 non-core packages
> Url is: https://ccmdls.adobe.com/AdobeProducts/COMP/1.0.5/osx10/afb9a6ca-08d0-4322-94c8-a4c55ac83cfb/AdobeColor_MotionPicture_1_0-mul.zip
> [COMP_1.0] Downloading AdobeColor_MotionPicture_1_0-mul.zip
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.54M/2.54M [00:00<00:00, 46.8MiB/s]
> Url is: https://ccmdls.adobe.com/AdobeProducts/COMP/1.0.5/osx10/afb9a6ca-08d0-4322-94c8-a4c55ac83cfb/AdobeColor_VideoProfilesAE_1_0-mul.zip
> [COMP_1.0] Downloading AdobeColor_VideoProfilesAE_1_0-mul.zip
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.7k/25.7k [00:00<00:00, 34.0MiB/s]
> [CCXP_2.2.1] Parsing available packages
> [CCXP_2.2.1] Selected 1 core packages and 0 non-core packages
> Url is: https://ccmdls.adobe.com/AdobeProducts/CCXP/2.2.1.120/osx10-64/856988a2-0933-4098-9c21-082ae9d1fe8f/CCX-Process-mul.zip
> [CCXP_2.2.1] Downloading CCX-Process-mul.zip
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29.1M/29.1M [00:00<00:00, 35.3MiB/s]
> 
> Generating driver.xml
> 
> Package successfully created. Run /private/tmp/Install AEFT_18.4.1-en_US-osx10-64.app to install.
> 
> 
> Do you want to create another package (Y/n): 
> ```

Hi I just get this, everything seems fine other than the absence of AEFT. I don't know what I did wrong, when I write AEFT it says, Please enter the SAP Code of the desired product (eg. PHSP for Photoshop): AEFT
AEFT is not a valid SAP Code. Please use a value from the list above.
(I did try the AEFT Beta but since there's no Adobe Zii patcher for it yet, I can't really use it. 
![3FE9FEFA-515F-46E7-8A3A-F0D199AC05BC](https://user-images.githubusercontent.com/96028353/147625152-1b7c2c87-542f-462b-8354-3a5496dfb3f2.JPG)
g

**Comment by thpryrchn** [comment]
You may be running an old version of the script. Delete the `Adobe Packager.command` from your application folder, and download from this git, and try again.

**Comment by thpryrchn** [comment]
@gird34 No Problem wit the script.... There is no release version that is M1 native.  hence why the script shows:
```
Note: If the Adobe program is not listed here, there is no native M1 version.
      Use the non native version with Rosetta 2 until an M1 version is available.
```
So, either make a Intel version, or a Beta version.

**Comment by gird34** [comment]
How do I make the intel version?

**Comment by thpryrchn** [comment]
Answer no to the first question when you start the script that askes if you want to make M1 version. 

It defaults to yes when running from a m1 Mac, and no when ran from Intel.

**Comment by gird34** [comment]
Ahhh ok thank you
