### ISSUE TITLE
Error 182 when trying to install a package

### ISSUE THREAD

**Issue by itsab1989** [Drovosek01/adobe-packager#24]
I was using adobe packager to download the latest versions of PS and AI, but the installation always aborts with the error 182. The log files say that the files for en_US are missing although I downloaded the de_DE version (my Mac only uses German language). When I create another package with the en_US language files and then copy them to the de_DE package the installation works flawless. Could you maybe add an option to always include the en_US language files even if another language is selected? IT would make the whole process a little easier and faster. Thanks in advance!

Edit: Just had another look at the contents of the packages. The installers for en_US also included the de_DE files, but not vice verso. Is there a reason for that?

**Comment by mackonsti** [comment]
Hi @itsab1989 I was wondering if your macOS system language is not English but German? Not sure if the downloader considers system language altogether, hence your error 182; just a thought but @Drovosek01 is the best person to reply.

**Comment by itsab1989** [comment]
Yes my system language is German. But when I download a package with German language the installation aborts, because the english files are missing

**Comment by itsab1989** [comment]
I was thinking about downloading the en_US versions, because it includes the German language files as well. Saves some space this way.

**Comment by thpryrchn** [comment]
When I get some time, I may incorporate an option to add more languages that the OS detected language, and specified language. But I am super Busy in my Matrix life :)

**Comment by thpryrchn** [comment]
> Yes my system language is German. But when I download a package with German language the installation aborts, because the english files are missing

Being that I am English native, and not know any other languages, and in the US, I haven't had problems with Languages... But you are saying that on a German native MacOS, with the German language selected, it still needs us_EN? If that is the case, I wonder if the Script needs to always include en_US no matter what other Language is selected.

**Comment by itsab1989** [comment]
Yes, that is exactly what I mean. I never had this issue before, when I downloaded installers with adobe packager. But suddenly I got this error message...
Nowadays you cannot even download trials with the Creative Cloud application, because Adobe wants your credit card information before they allow you to download a trial version. So the packager is more important for me than it has ever been.

**Comment by thpryrchn** [comment]
> Edit: Just had another look at the contents of the packages. The installers for en_US also included the de_DE files, but not vice verso. Is there a reason for that?

This is because when the script detects a system version that is different than the selected, it installs the selected and detected.

**Comment by waipeinan** [comment]
how do I add all languages when running the script, as I am still at Failed with error code 182 when trying to install MUSE

**Comment by thpryrchn** [comment]
Type ALL for Language.
