### ISSUE TITLE
Please add option "q" to gracefully quit script at any time

### ISSUE THREAD

**Issue by mackonsti** [Drovosek01/adobe-packager#25]
Hello @Drovosek01 thank you again for your great work.
Please, can you kindly consider adding "q" as an option, at any moment there is a user-input, to gracefully quit your script?
(provided there are no temporary files, I guess)
I think it's better to quit the running process internally via "q" at input, rather than Ctrl+C instead.
This is convenient when checking for version numbers for example, without the need to download or package anything.
Thanks for your consideration!

**Comment by thpryrchn** [comment]
CTRL-C Is safe, as there are no files written until the final step. everything is in RAM until it downloads the packages.

**Comment by mackonsti** [comment]
Thank you for your consideration @thpryrchn
