### ISSUE TITLE
code error 195,127 and 107

### ISSUE THREAD

**Issue by mysteriousflower** [Drovosek01/adobe-packager#33]
I have a mac 10.13.6 and tried to download the oldest versions of Lightroom, premier pro and photoshop and have received all of those codes. I'm not sure what I can do to solve this please help>.<

**Comment by Drovosek01** [comment]
What do you want and what is problem?

**Comment by Drovosek01** [comment]
Dude, you're not on the "battle of the psychics" show. Write the full version of your mac OS and the names and versions of the applications that you are trying to download through the script.

Why should I pry this information out of you?

**Comment by mysteriousflower** [comment]
Sorryyyyy This is my first time dong anything like this.... my mac is 10.13.6I tried to do lightroom 4.1 premiere pro 15.2 and photoshop 16.0

**Comment by mysteriousflower** [comment]
Thank you for your help sir I am very grateful XD

**Comment by thpryrchn** [comment]
Works fine on my computer... May need to install Python 3
