### ISSUE TITLE
Failed with error code 103 - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by aromart** [Drovosek01/adobe-packager#34]
Creating Install PHSP_22.5.1-es_ES-macarm64.app on MacBookPro18,2
When running the installer it raises "Failed with error code 103"
Looking back to the terminal window where the file was created one can read:

`
sapCode: PHSP
version: 22.5.1
installLanguage: es_ES
dest: /Users/romar/Downloads/Install PHSP_22.5.1-es_ES-macarm64.app
[{'sapCode': 'PHSP', 'version': '22.5.1', 'buildGuid': '55a47fbd-a836-4fd3-995d-33d2d277b29b'}, {'sapCode': 'ACR', 'version': '9.6', 'buildGuid': '3fc409fc-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'COCM', 'version': '1.0', 'buildGuid': '3fc3cb53-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'COSY', 'version': '2.4.1', 'buildGuid': '3fcf9f00-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'CORG', 'version': '1.0', 'buildGuid': '3fc3cf0a-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'CORE', 'version': '1.0', 'buildGuid': '3fc3d387-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'COPS', 'version': '1.0', 'buildGuid': '3fc3df37-c3fa-11e9-b9c5-12148b63a89a'}]

Creating Install PHSP_22.5.1-es_ES-macarm64.app
.: replacing existing signature

Preparing...

[PHSP_22.5.1] Downloading application.json
[PHSP_22.5.1] Creating folder for product
[PHSP_22.5.1] Saving application.json

[ACR_9.6] Downloading application.json
Traceback (most recent call last):
  File "./ccdl.py", line 655, in <module>
    runccdl()
  File "./ccdl.py", line 546, in runccdl
    app_json = get_application_json(p['buildGuid'])
  File "./ccdl.py", line 321, in get_application_json
    return json.loads(r(ADOBE_APPLICATION_JSON_URL, headers))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Proceso completado]
`

Any thoughts?

**Comment by thpryrchn** [comment]
Try making your install package with all languages.

**Comment by DennisdeWitNL** [comment]
I have the same issue.

**Comment by Ternoc** [comment]
I lunched the script with sudo and it worked that way

**Comment by aromart** [comment]
It worked for me when I created the non-M1 package.
