### ISSUE TITLE
Photoshop 23.3 is missing

### ISSUE THREAD

**Issue by badboy996** [Drovosek01/adobe-packager#35]
Photoshop 23.3 since isn't available in Adobe Packager,After Effects 22.3 neither

**Comment by sshrmr** [comment]
same here

**Comment by Drovosek01** [comment]
Yes, I am aware of this problem. Adobe has changed the API and now new applications can be obtained, for example, by POST request to `https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v5/products/all?channel=ccm&channel=sti&channel=services&channel=mobileApps&platform=macuniversal,osx10-64,osx10&clientPlatform=osx10-64&_type=xml&productType=Desktop&payload=true`
with headers
```
Host: prod-rel-ffc-ccm.oobesaas.adobe.com
Content-Type: application/json
x-adobe-app-id: accc-apps-panel-desktop
```
, but not all the latest applications are there and additional time is needed for traffic analysis and script modification

**Comment by Drovosek01** [comment]
Fixed
