### ISSUE TITLE
Failed to launch task: Bad CPU type in executable

### ISSUE THREAD

**Issue by gingerbeardman** [Drovosek01/adobe-packager#39]
- I don't have Rosetta2 installed.
- I chose to make native M1 packages
- I generated `Install PHSP_23.3.2-en_GB-macuniversal`

When I run the installer:
1. prompt to start install
2. prompt for password
3. error "Failed to launch task: The operation couldn’t be completed. Bad CPU type in executable"

This is surprising as it implies some part of the installer is Intel only.

## Screenshot

<img width="420" alt="Screen shot 2022-06-09 at 17 00 16" src="https://user-images.githubusercontent.com/49612/172892971-b61b3b67-b051-4b1b-b267-b6bbc1bc74d5.png">

**Comment by thpryrchn** [comment]
Do you have Rosetta installed?

If not, Install it.

**Comment by gingerbeardman** [comment]
Disappointing response.

**Comment by kratos9394** [comment]
i am intel version,got bad cpu too
