### ISSUE TITLE
error 182 while installing

### ISSUE THREAD

**Issue by sergiobaiao** [Drovosek01/adobe-packager#4]
For those of you getting an error 182 while trying to install, check the log file. Open terminal, and type:

sudo nano /Library/Logs/Adobe/Installers/Install.log

go to the end of the file and check for errors. I had downloaded the en_US file but somehow the installer was trying to install pt_BR which is my default OS language. I then downloaded the pt_BR and it worked. I also copied the missing file inside the en_US Contents, like the log said, and it installed both en_US and pt_BR versions.

**Comment by thpryrchn** [comment]
Interesting.  I have only messed with en_us, as that is native for me. 

So you are saying that it is erroring out because you are installing on a different system language?

I wonder if the script could be changed and download all languages.  Then again it would take more space.

**Comment by sergiobaiao** [comment]
Yes, somehow it`s default the installation language to the default OS language. I think that this is the CC installer doing this. After i copied the correct language file inside the en_US Contents/products/..../ folder it installed both

**Comment by evankervella** [comment]
Oh men, thank you so much. I was digging Reddit for DAYS and you described the exact solution! So grateful :)

**Comment by thpryrchn** [comment]
Let me know if the Latest commits have fixed the issue!

I have even added the option to download all Languages if you select ALL as the language.

**Comment by DTSREYES** [comment]
Tengo este mismo error, utilizo win11 y no he podido corregirlo
