### ISSUE TITLE
runccdl error

### ISSUE THREAD

**Issue by Privatexoxo** [Drovosek01/adobe-packager#42]
python3 found!
requests found!
starting ccdl
=================================
= Adobe macOS Package Generator =
============= 0.1.4 =============

Do you want to make M1 native packages (Y/n): Y
Downloading products.xml

https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Source URL is: https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Source URL is: https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macarm64,macuniversal&productType=Desktop
Parsing products.xml
Traceback (most recent call last):
  File "/Users/Downloads/adobe-packager-master 2/./ccdl.py", line 662, in <module>
    runccdl()
  File "/Users/Downloads/adobe-packager-master 2/./ccdl.py", line 369, in runccdl
    products, cdn = parse_products_xml(products_xml)
  File "/Users/Downloads/adobe-packager-master 2/./ccdl.py", line 283, in parse_products_xml
    dependencies = list(
TypeError: 'NoneType' object is not iterable

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by NizNoz78** [comment]
Exactly the same error here, except I wanted to make a non-native package.
M1 Macbook Pro, macOS Monteray 12.4. Happens every time I run the ccdl.command

python3 found!
requests found!
starting ccdl
=================================
= Adobe macOS Package Generator =
============= 0.1.4 =============

Do you want to make M1 native packages (Y/n): n
Downloading products.xml

https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Source URL is: https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Parsing products.xml
Traceback (most recent call last):
  File "/Users/nizaarlilla/Downloads/adobe-packager-master/./ccdl.py", line 662, in <module>
    runccdl()
  File "/Users/nizaarlilla/Downloads/adobe-packager-master/./ccdl.py", line 369, in runccdl
    products, cdn = parse_products_xml(products_xml)
  File "/Users/nizaarlilla/Downloads/adobe-packager-master/./ccdl.py", line 283, in parse_products_xml
    dependencies = list(
TypeError: 'NoneType' object is not iterable
logout

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by thpryrchn** [comment]
Just tested with a FRESH download of the code, and it works fine!!! Delete your adobe-packager folder, and do a `git clone https://github.com/Drovosek01/adobe-packager.git`
