### ISSUE TITLE
Hi! I downloaded installer "Install MUSE_2018.1.0-en_US-osx10-64.app" but "installation Failed code 182"

### ISSUE THREAD

**Issue by vovation** [Drovosek01/adobe-packager#48]
Hi! Could you help me? How to install this package? Every time I get same error "installation Failed code 182".
Tried MUSE_2018.1.0 and MUSE_2018.1.1. Every time same error... I use Mac OS Catalina 10.15.5, Macbook with Intel core, personal creative cloud account 
Thank you!

**Comment by Drovosek01** [comment]
This error has nothing to do with Adobe Packager.
