### ISSUE TITLE
0.1.4 doesn't support downloading new Adobe Substance tools

### ISSUE THREAD

**Issue by Mancerrss** [Drovosek01/adobe-packager#5]
Based on looking somewhere else, the earlier script `0.1.2-hotfix1` **does support downloading and detecting [Adobe Substance](https://www.adobe.com/creativecloud/3d-augmented-reality.html)** tools. However. It **doesn't ask you to create an M1 package at the start.**

Meanwhile the latest version `0.1.4` **does support** asking and presumably **creating M1 packages**, it's just it **doesn't know** how to **display and obtain Adobe Substance tools**.

<img width="842" alt="Screen Shot 2021-09-14 at 11 27 16 AM" src="https://user-images.githubusercontent.com/20938829/133191968-e7f8925e-9155-4d32-b480-bfc837a9bc34.png">
<img width="842" alt="Screen Shot 2021-09-14 at 11 27 41 AM" src="https://user-images.githubusercontent.com/20938829/133191992-8bb79e80-18b0-46f7-ade2-bbac7ea8044e.png">

This is [where the earlier version](https://gist.github.com/ayyybe/a5f01c6f40020f9a7bc4939beeb2df1d) of the script lives on. 

`/bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/ayyybe/a5f01c6f40020f9a7bc4939beeb2df1d/raw/install.sh)"` to execute.

Please investigate, why this one was able to show the Substance tools, unlike your newer script.
Can you guys fix this soon? Pretty sure this is just a quick fix.

- [ ] Support displaying and downloading Adobe Substance tools
- [ ] Support creating M1 packages for Adobe Substance tools.

**Thanks**

**Comment by Drovosek01** [comment]
Perhaps when you select the versions of programs for ARM when running the script, programs that can work natively on the ARM processor are displayed and perhaps Substance has not yet been optimized for native work on ARM.

If you have a Mac on M1, you can easily check this. Download the Substance application via Creative Cloud, then go to the application folder in the Finder and right-click on the application -> Get Info.
If it says "(Apple) " or " (Universal)", then the application can work natively on ARM, but if it says "(Intel)", then I think this will be the answer to your question.

**Comment by Mancerrss** [comment]
@Drovosek01 Yup. Can confirm, Substance tools only show when you `n` when being asked if you want to create an M1 package. So it's not because the script didn't support showing up this new Substance tools. It's just because the script haven't support M1 yet. As Substance still isn't universal and supports M1 natively.

I do think they run on Rosetta 2 tho, haven't tried it yet, will test later.

**_My suggestion would be_** : when there's other apps in the M1 list that isn't showing up, when you picked M1 package, display in grey text maybe "The following apps isn't available and optimized on M1. They are not guaranteed to with Rosetta 2 : _then the list of apps will be listed below in Grey text_" so I guess this kind of confusion would not be repeated again.

**Comment by thpryrchn** [comment]
If a package doesn't show up when hitting Y for M1 packages, then it is Intel native only, and should still work with Rosetta 2. 

That is why there are LESS programs for M1. 

Nothing We can do to get M1 versions of Apps that Adobe hasn't made...

Also noting, most M1 versions install Universal binarys. I am guessing that they have stripped versions for Intel only to save on CDN costs.
> Based on looking somewhere else, the earlier script `0.1.2-hotfix1` **does support downloading and detecting [Adobe Substance](https://www.adobe.com/creativecloud/3d-augmented-reality.html)** tools. However. It **doesn't ask you to create an M1 package at the start.**
> 
> Meanwhile the latest version `0.1.4` **does support** asking and presumably **creating M1 packages**, it's just it **doesn't know** how to **display and obtain Adobe Substance tools**.
> 
> <img alt="Screen Shot 2021-09-14 at 11 27 16 AM" width="842" src="https://user-images.githubusercontent.com/20938829/133191968-e7f8925e-9155-4d32-b480-bfc837a9bc34.png">
> 
> <img alt="Screen Shot 2021-09-14 at 11 27 41 AM" width="842" src="https://user-images.githubusercontent.com/20938829/133191992-8bb79e80-18b0-46f7-ade2-bbac7ea8044e.png">
> 
> This is [where the earlier version](https://gist.github.com/ayyybe/a5f01c6f40020f9a7bc4939beeb2df1d) of the script lives on.
> 
> `/bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/ayyybe/a5f01c6f40020f9a7bc4939beeb2df1d/raw/install.sh)"` to execute.
> 
> Please investigate, why this one was able to show the Substance tools, unlike your newer script.
> Can you guys fix this soon? Pretty sure this is just a quick fix.
> 
>     * [ ]  Support displaying and downloading Adobe Substance tools
> 
>     * [ ]  Support creating M1 packages for Adobe Substance tools.
> 
> 
> **Thanks**
