### ISSUE TITLE
Adobe InDesign damaged and can't be opened

### ISSUE THREAD

**Issue by nicsg99** [Drovosek01/adobe-packager#51]
A pop up window shows up when I open Indesign saying "“Adobe InDesign 2020” is damaged and can’t be opened. You should move it to the Bin.".

How can I resolve this issue?

**Comment by JoeyTeng** [comment]
You can try to use `xattr -r -d com.apple.quarantine <path to file or app>` in terminal. Reference: https://appletoolbox.com/app-is-damaged-cannot-be-opened-mac/#Use_the_Xattr_Command

**Comment by Idomo** [comment]
For me it just asked for a permission in System Preferences > Security > Choose allow when it said that you may not trust InDesign.
