### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by wimstrydom** [Drovosek01/adobe-packager#6]
When attempting to run the packager, I get the following issue:

Traceback (most recent call last):
  File "./ccdl.py", line 33, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

I have tried manually installing the 'requests' module from [here](https://pypi.org/project/requests/#files), but this doesn't seem to have had any effect.

**Comment by yozhic** [comment]
@wimstrydom,
```sh
pip3 install requests
```

**Comment by wimstrydom** [comment]
@yozhic 

Tried this, but I get the following error:

ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/index/__init__.py)

Apologies if this is actually just actually just an issue with my setup (which I'm starting to think it is) and not specific to the packager.

**Comment by yozhic** [comment]
@wimstrydom, just [let's try to fix it](https://stackoverflow.com/questions/59887436/importerror-cannot-import-name-packagefinder).

**Comment by wimstrydom** [comment]
@yozhic It worked, thank you so much! Packager works now
