### ISSUE TITLE
Error Bad CPU type in executable

### ISSUE THREAD

**Issue by Chezoit** [Drovosek01/adobe-packager#61]
Hi,
When I try to install ''Install PHSP_24.4.1-fr_FR-macuniversal'' I get this message ''Failed to launch task: The operation couldn’t be completed. Bad CPU type in executable''

I Use OpenCore-Legacy-Patcher 0.6.6 on  Macbook air Dual-Core i7 (6,2) / Ventura 13.4.
(https://github.com/dortania/OpenCore-Legacy-Patcher)

**Comment by Drovosek01** [comment]
Show scrennshot with error

**Comment by Chezoit** [comment]
Only this message : "Failed to launch task: The operation couldn’t be completed. Bad CPU type in executable''

<img>https://i.ibb.co/kc8PHCw/Screenshot-2023-05-24-at-11-20-57-AM.png</img>

**Comment by Chezoit** [comment]
The same message with OpenCore-Legacy-Patcher 0.6.7.

**Comment by Chezoit** [comment]
New error message with Adobe macOS Package Generator 0.2.0 : https://github.com/Drovosek01/adobe-packager/issues/66
