### ISSUE TITLE
Need help for research new xml and Python parse... for download Photoshop BETA

### ISSUE THREAD

**Issue by Drovosek01** [Drovosek01/adobe-packager#62]
If someone wants to download the latest Photoshop Beta (currently the latest version is 24.6), then in the file `ccdl.py` need to change this URL
`https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform={installPlatform}&productType=Desktop`
to this
`https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v5/products/all?_type=xml&channel=ccm,sti&platform={installPlatform}&productType=Desktop`

Or just change `v4` to `v5` in URL.

And after running the script and selecting PHSPBETA, you will see the latest version of Photoshop.

![image](https://github.com/Drovosek01/adobe-packager/assets/29478700/141db157-1097-425d-a846-fc835f8036e7)

Unfortunately, when you try to download it, it will be an error. Probably something has changed in the response from URL v5, something in the xml structure that came in the response.

As I wrote in the Readme, I am not the author of this script. I don't have the skills to work with Python and XML research yet

**Comment by nmcc1212** [comment]
I've got it working here https://github.com/nmcc1212/adobe-packager

but still getting the Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700) (#56)

**Comment by nmcc1212** [comment]
btw if anyone needs a *working* download for 24.6, my discord is macki#2525

**Comment by Drovosek01** [comment]
> I've got it working here https://github.com/nmcc1212/adobe-packager to the point that i get a package file with no errors

Thanks for trying.

I have just tested the version with your changes and unfortunately the installers made with your changes do not work and immediately give error 103. I have researched this and the problem is that with your changes, for some reason, the CCX component is not downloaded along with other components of the selected product.

Additional edits are needed

> but still getting the Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700) (#56)

Yes, this problem is discussed in a separate thread. To solve it, you need to use Creative Cloud v5.7.0

**Comment by jesussmile** [comment]
> btw if anyone needs a _working_ download for 24.6, my discord is macki#1525

Hey can you share it ?

**Comment by jesussmile** [comment]
Just add a placeholder for `productsIntel` like this and it should get you thru the downloads successfully. Yea getting an error 103 when extracting the package afterwards. Unsure what it is, its mostly likely to do with the version conflict between CC and photoshop, may be ? 
```dart 

    print('')
    productsintel = {
    'sapCode': 'version',
    'version': '2.2.1',  # Add the necessary values for each sapCode
}

    prodInfo = versions[version]
    prods_to_download = []
    dependencies = prodInfo['dependencies']
    for d in dependencies:
     try:
         prods_to_download.append({
             'sapCode': d['sapCode'],
             'version': d['version'],
             'buildGuid': products[d['sapCode']]['versions'][d['version']]['buildGuid']
         })
     except KeyError:
         try:
             prods_to_download.append({
                 'sapCode': d['sapCode'],
                 'version': d['version'],
                 'buildGuid': productsintel[d['sapCode']]['versions'][d['version']]['buildGuid']
             })
         except KeyError:
             print(f"Error: buildGuid not found for sapCode: {d['sapCode']}, version: {d['version']}")
```

**Comment by Antibioticss** [comment]
Bruh, that's my installer.
I've fixed this issue and updated some new features. Get it from [here](https://github.com/Antibioticss/adobe-packager).
No sure if there will be new issues, I would like to test it out before I pull a request.
Welcome to add issues. 😀

**Comment by nmcc1212** [comment]
idk if your talking about my link, but i found that link on a forum

**Comment by Antibioticss** [comment]
I know, it's from MSJ. I posted it there. ;)

**Comment by jesussmile** [comment]
> I know where it's from. I posted it there. ;)

Yo! What was the issue initially giving out all the errors mentioned above ? What did u fix?

**Comment by Antibioticss** [comment]
You can see my commit [here](https://github.com/Antibioticss/adobe-packager/commit/d502478ab1c89bd9dbb80b30e5399dce2ac41ff3)
This is actually a mistake in parsing dependencies.

**Comment by jesussmile** [comment]
> You can see my commit [here](https://github.com/Antibioticss/adobe-packager/commit/d502478ab1c89bd9dbb80b30e5399dce2ac41ff3) This is actually a mistake in parsing dependencies.

Thank you. Great find! Appreciate it bud.

**Comment by nmcc1212** [comment]
> I know where it's from. I posted it there. ;)

mb lol, thanks for putting it there :)

**Comment by jesussmile** [comment]
> You can see my commit [here](https://github.com/Antibioticss/adobe-packager/commit/d502478ab1c89bd9dbb80b30e5399dce2ac41ff3)
> This is actually a mistake in parsing dependencies.

yo! how to crack it?

**Comment by Drovosek01** [comment]
Fixed with merge commits by @Antibioticss

**Comment by Antibioticss** [comment]
> yo! how to crack it?

Just read my code, it's not difficult to understand.

**Comment by KaipiYann** [comment]
> Just read my code, it's not difficult to understand.
@Antibioticss where to read cause I'm stuck with trial mode of PS and didn't see anything in code about this.

**Comment by Antibioticss** [comment]
Em, I mean the code for fixing the v5 url. And this repo is not for Adobe warez.
