### ISSUE TITLE
Error when installing error 103 (solutions in closed topic dont work) + a new one now:  Unexpected EOF (-2700)

### ISSUE THREAD

**Issue by tcasm** [Drovosek01/adobe-packager#63]
Hello, first of all thanks a lot for this wonderful solution, but (sadly) i've been unable to install the downloaded packages.
I'm running on an Intel Mac, and getting the "error 103" when trying to install the program: i tried in sudo mode, downloading all the languages... and still don't work.

I updated the Creative cloud app, and now I'm getting a new error:
Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)

¿can somebody shine some light on what may be happening? Trying to install indesign :)

Thanks a lot!

**Comment by Antibioticss** [comment]
Take a look at [here](https://github.com/Drovosek01/adobe-packager/issues/56), you need old version of ACC to install.

**Comment by tcasm** [comment]
Thanks for that, I tried it, but when i patch it, I'm back to error 103, and i do everything on the closed thread.... and nothing. Thannks a lot for your help, i dont know how i missed that thread!

**Comment by Drovosek01** [comment]
I wrote about error 103 here - https://github.com/Drovosek01/adobe-packager/issues/62#issuecomment-1578521022

Now I revert last commit. All should work, but we still need find method to download Photoshop Beta installer
