### ISSUE TITLE
(Maybe feature request) Possible to run without ACC?

### ISSUE THREAD

**Issue by miyuanbo** [Drovosek01/adobe-packager#67]
Would it be possible to run the packager with only AntiCC or CC Runtime?

**Comment by Antibioticss** [comment]
Actually it works well with AntiCC

**Comment by miyuanbo** [comment]
but I encounter https://github.com/Drovosek01/adobe-packager/issues/56

**Comment by Antibioticss** [comment]
In my test, it works well with AntiCC 1.7
You can download it from here: https://www.mediafire.com/file/q01nd5grk6m7se8/AntiCC_1.7_%255BRiD%255D.dmg/file

**Comment by miyuanbo** [comment]
Oh thanks, I've tried AntiCC 1.7 and it works!
