### ISSUE TITLE
PHSP still want money

### ISSUE THREAD

**Issue by milac-malisnae** [Drovosek01/adobe-packager#86]
Hello all, thanks a lot for all those conversations that help me a lot to go each time further to the sacred graal ! I followed different stuff and finally was able to run the "installPHSP_25.7" installer, I used the AntiCC advice from another issue (about json 2700) and It indeed charged PHSP. However, when I run PHSP, it still asks me to make a subscription, exactly like the crack didn't work. Is there any step I could have missed ? Thanks a lot for your help, by advance !

**Comment by Drovosek01** [comment]
This repo not for crack or alternative activate.

This repo for original installers only.
